#!/bin/bash

# This script help move self-defined bin files to usr/local/bin
# Usage: mvcon <bin_file_name>

help() {
    echo "Usage: mvbin <bin_file_name>"
    echo " ------------------------------- "
    echo "    bin_file_name: in ~/.scripts/utils/"
    exit 1
}

# Check if ~/.scripts/utils folder exist
if [[ ! -d ~/.scripts/utils ]]; then
    echo "The ~/.scripts/utils folder doesn't exist"
    echo "Create the ~/.scripts/utils folder"
    mkdir -p ~/.scripts/utils
fi

# If not in .script folder, move to .script folder
if [[ ! $PWD == *".scripts/utils"* ]]; then
    echo "Move to .scripts/utils folder"
    cd ~/.scripts/utils
fi


# Define 
BIN_PATH_DEFAULT=/usr/local/bin
BIN_PATH=/usr/local/bin/
input=$1

# Check if the input is empty
if [[ -z $input ]]; then
    echo "Please input the bin file name"
    help
    exit 1
fi

# Make input executable
if [[ ! -x $input ]]; then
    echo "Make $input executable"
    chmod +x $input
fi

# If the input has extension, remove it
if [[ $input == *"."* ]]; then
    echo "Remove the extension of $input"
    input=${input%.*}
fi


# Function to get user confirmation
get_confirmation() {
    read -p "Are you sure to move $BIN_PATH$input to $BIN_PATH ? [y/n]" -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Abort"
        exit 1
    fi
}

# Check if the BIN_PATH is in $PATH
if [[ ":$PATH:" != *":$BIN_PATH_DEFAULT:"* ]]; then
    echo "The $BIN_PATH_DEFAULT is not in \$PATH"
    echo "Add $BIN_PATH_DEFAULT to \$PATH"
    echo "export PATH=$PATH:$BIN_PATH_DEFAULT" >> ~/.bashrc 
    source ~/.bashrc
fi

# Check if the INPUT bin exist inside BIN_PATH: if not, create, else update them

if [[ -f $BIN_PATH$input ]]; then
    echo "The $input is already exist in $BIN_PATH"
    get_confirmation
    echo "Update the $input"
    sudo cp $input $BIN_PATH
else
    echo "The $input is not exist in $BIN_PATH"
    get_confirmation
    echo "Create the $input, and make it executable"
    sudo chmod +x $input
    echo "Copy the $input to $BIN_PATH"
    sudo cp $input $BIN_PATH
    sudo mv $BIN_PATH$input $BIN_PATH$input
fi
